# Generated by Django 5.0.3 on 2024-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('resumido', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
