# Generated by Django 4.2.9 on 2024-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('porcentaje', models.FloatField()),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
