# Generated by Django 5.0.3 on 2024-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Impuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
