# Generated by Django 4.2.9 on 2024-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PresupuestoCliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocliente',
            name='exentas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestocliente',
            name='iva_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestocliente',
            name='iva_5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
