# Generated by Django 4.2.10 on 2024-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PresupuestoCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepresupuestocliente',
            name='total_linea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuestocliente',
            name='total_presupuesto',
            field=models.IntegerField(),
        ),
    ]
