# Generated by Django 4.2.10 on 2024-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PresupuestoCliente', '0002_alter_presupuestocliente_estado_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocliente',
            name='estado_presupuesto',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
