# Generated by Django 4.2.9 on 2024-03-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PresupuestoCliente', '0002_presupuestocliente_exentas_presupuestocliente_iva_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuestocliente',
            name='iva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
