# Generated by Django 4.2.9 on 2024-03-08 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clasificaciones', '0001_initial'),
        ('Impuestos', '0001_initial'),
        ('UnidadMedida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('codigo_barra', models.CharField(max_length=250)),
                ('codigo_remitido', models.CharField(max_length=250)),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('precio_mayorista', models.FloatField()),
                ('existencia', models.IntegerField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clasificaciones.clasificaciones')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Impuestos.impuestos')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UnidadMedida.unidadmedida')),
            ],
        ),
    ]
