# Generated by Django 4.2.9 on 2024-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo_remitido',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
