# Generated by Django 4.2.10 on 2024-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('documento', models.CharField(max_length=250, unique=True)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('observacion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
            ],
        ),
    ]
