# Generated by Django 4.2.9 on 2024-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ruc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
